version: '3.8'

services:
  backend:
    build: .
    command: >
      sh -c "
      echo 'Waiting for database...' &&
      until pg_isready -h db -U postgres; do sleep 2; done &&
      
      echo 'Running migrations...' &&
      cd /app/backend && alembic upgrade head &&

      
      echo 'Starting Uvicorn...' &&
      exec uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./backend:/app/backend
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONPATH: "/app"
      PYTHONUNBUFFERED: 1
      

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    profiles:
      - frontend
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "restaurant"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db  # Автоматически создаст эту БД
    ports:
      - "5432:5432"
      
volumes:
  postgres_data: