"""same

Revision ID: a49a5aee0ae9
Revises: 41a309ec9d58
Create Date: 2025-04-11 17:15:54.631701

"""

# revision identifiers, used by Alembic.
revision = 'a49a5aee0ae9'
down_revision = '41a309ec9d58'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reservation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('reservations_table_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tables', ['table_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservations_table_id_fkey', 'tables', ['table_id'], ['id'])
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reservation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
